<?php
/* THIS FILE IS GENERATED BY: ./utilities/PhpStorm/metaCreator.php */

namespace PHPSTORM_META {
    
    exitPoint(\CakeObject::_stop());
    exitPoint(\Controller::redirect());

    override(\ClassRegistry::init(0),
        map([
            'Datasource' => \Datasource::class,
            'User' => \User::class,
        ])
    );

    expectedArguments(\Factory::compose(),
        0,
        'Datasource',
        'User',
    );
}
